version: "2"
services: 
  app: 
    image: "nginx:1.15.8-alpine"
    restart: "always"
    networks: 
      - "web"
    ports: 
      - "5000:5000"
    volumes: 
      - "./build/:/var/www/html/web"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
networks: 
  web: 
    external: true
